CREATE TABLE `User`
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(100) NOT NULL,
    Password VARCHAR(100) NOT NULL,
    Active BOOLEAN NOT NULL,
    IsDeleted BOOLEAN NOT NULL,
    PersonId INT UNIQUE NOT NULL
);

CREATE TABLE Person
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL,
    Address VARCHAR(50) NOT NULL,
    IsDeleted BOOLEAN NOT NULL
);

CREATE TABLE RolUser
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    RolId INT NOT NULL,
    UserId INT NOT NULL,
    IsDeleted BOOLEAN NOT NULL
);

CREATE TABLE Rol
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Code VARCHAR(1000) NOT NULL,
    IsDeleted BOOLEAN NOT NULL,
    CreateAt TIMESTAMP NOT NULL,
    DeleteAt TIMESTAMP NULL
);

CREATE TABLE RolFormPermission
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    RolId INT NOT NULL,
    FormId INT NOT NULL,
    PermissionId INT NOT NULL,
    IsDeleted BOOLEAN NOT NULL
);

CREATE TABLE Permission
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    Description TEXT NOT NULL,
    IsDeleted BOOLEAN NOT NULL
);

CREATE TABLE Form
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    Description TEXT NOT NULL,
    IsDeleted BOOLEAN NOT NULL
);

CREATE TABLE FormModule
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ModuleId INT NOT NULL,
    FormId INT NOT NULL,
    IsDeleted BOOLEAN NOT NULL
);

CREATE TABLE Module
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description TEXT NOT NULL,
    IsDeleted BOOLEAN NOT NULL
);

-- Relaciones

-- User - Person
ALTER TABLE `User` ADD CONSTRAINT FK_User_Person FOREIGN KEY (PersonId) REFERENCES Person(Id);

-- RolUser - User
ALTER TABLE RolUser ADD CONSTRAINT FK_RolUser_User FOREIGN KEY (UserId) REFERENCES `User`(Id);

-- RolUser - Rol
ALTER TABLE RolUser ADD CONSTRAINT FK_RolUser_Rol FOREIGN KEY (RolId) REFERENCES Rol(Id);

-- Module - Form
ALTER TABLE FormModule ADD CONSTRAINT FK_FormModule_Module FOREIGN KEY (ModuleId) REFERENCES Module(Id);
ALTER TABLE FormModule ADD CONSTRAINT FK_FormModule_Form FOREIGN KEY (FormId) REFERENCES Form(Id);

-- RolFormPermission - Rol - Form - Permission
ALTER TABLE RolFormPermission ADD CONSTRAINT FK_RolFormPermission_Rol FOREIGN KEY (RolId) REFERENCES Rol(Id);
ALTER TABLE RolFormPermission ADD CONSTRAINT FK_RolFormPermission_Form FOREIGN KEY (FormId) REFERENCES Form(Id);
ALTER TABLE RolFormPermission ADD CONSTRAINT FK_RolFormPermission_Permission FOREIGN KEY (PermissionId) REFERENCES Permission(Id);